---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Version 1.0.0
# Author: Thoughts & Ideas <hello@thoughtsandideas.uk>

name: 'Auto Merge'

on:
  pull_request_review:
    types:
      - 'submitted'

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  approved:
    name: 'Approve Pull Request'
    runs-on: 'ubuntu-latest'

    if: github.event.review.state == 'APPROVED'

    steps:
      - run: echo "This PR was approved"
